services:
  - type: web
    name: disaster-command-center-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://kanhaiya:patel@foodyham.anqqbp7.mongodb.net/disaster_db?retryWrites=true&w=majority
      - key: GROQ_API_KEY
        value: gsk_AQ.Ab8RN6L-QZFG_bfecBcLo3fV6_k4UlmiZLDgrG8REjvMcPlVUg
      - key: OPENWEATHER_API_KEY
        value: d1c14f51894941b551c264fa245fa531
      - key: ALLOWED_ORIGINS
        value: "*"
      - key: PYTHON_VERSION
        value: 3.11.0
